-- MySQL Script generated by MySQL Workbench
-- Sat Jun 29 20:41:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema basereserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basereserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basereserva` DEFAULT CHARACTER SET utf8 ;
USE `basereserva` ;

-- -----------------------------------------------------
-- Table `basereserva`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`consumidor` (
  `idpersona` INT NOT NULL,
  `codigo_consumidor` VARCHAR(45) NOT NULL,
  `idconsumidor` INT NOT NULL,
  UNIQUE INDEX `codigo_consumidor_UNIQUE` (`codigo_consumidor` ASC) VISIBLE,
  INDEX `fk_persona_consumidor_idx` (`idpersona` ASC) VISIBLE,
  PRIMARY KEY (`idconsumidor`),
  CONSTRAINT `fk_persona_consumidor`
    FOREIGN KEY (`idpersona`)
    REFERENCES `basereserva`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`consumo` (
  `idconsumo` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `cantidad` DECIMAL NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconsumo`),
  CONSTRAINT `fk_consumo_consumidor`
    FOREIGN KEY (`idconsumo`)
    REFERENCES `basereserva`.`consumidor` (`idconsumidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `estado` VARCHAR(45) NULL,
  `serviciocol` VARCHAR(45) NOT NULL,
  `tipo_servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idservicio`),
  CONSTRAINT `fk_consumo_servicio`
    FOREIGN KEY (`idservicio`)
    REFERENCES `basereserva`.`consumo` (`idconsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `idservicio` INT NOT NULL,
  `tipo_reserva` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `reservacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreserva`),
  CONSTRAINT `fk_reserva_consumo`
    FOREIGN KEY (`idreserva`)
    REFERENCES `basereserva`.`consumo` (`idconsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
